### ISSUE TITLE
Problem decrypting after encrypting with JS

### ISSUE THREAD

**Issue by freshking** [RNCryptor/rncryptor-js#1]
I have tried to implement the RNCryptor-js into a web app of mine but it doesn't seem to be working for me. Keep in mind I am a beginner in JS. The code I am using:

```
reader.onloadend = function(e) {
        var content = new Uint8Array(e.target.result);
                var utf8 = "";
                for (var i = 0, len = content.length; i < len; i++) {
                    utf8 += String.fromCharCode(content[i]);
                }

        var temp = RNCryptor.Encrypt(password,utf8,{rounds:1000});
        var encrypted = sjcl.codec.hex.fromBits(temp)

                a.attr('href', 'data:application/octet-stream,' + encrypted);
                a.attr('download', file.name);

                step(4);
            };
    reader.readAsArrayBuffer(file);
```

The file produced will not be able to be decrypted with the iOS RNCryptor implementation used successfully in other apps.

**Comment by rnapier** [comment]
Try https://github.com/RNCryptor/rncryptor-js/releases/tag/0.0.2. This may be too slow for real use; I'm not certain yet.

In my early tests, 10,000 PBKDF2 iterations (which is what RNCryptor requires) was taking minutes to calculate. But now it's taking less than a second, so I'm not certain what's going on there yet. But this version does pass the kdf and password test vectors.

There is no "rounds" option in the JS code. I was referring to the change that was required in _other_ implementations. But with 0.0.2, this shouldn't be necessary. (But still, I'm puzzling over why 10,000 rounds is running so quickly now.)
